#!/usr/bin/env python

"""Estimate the unit posteriors for each frame of the utterance."""

import argparse
import pickle
import amdtk
from numpy import sqrt, log

import kaldi_io


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--hmm_states', action='store_true',
                        help='output the hmm states posteriors')
    parser.add_argument('--ac_scale', type=float, default=1.0,
                        help='acoustic scale')

    parser.add_argument('model', help='model to fit on the data')
    parser.add_argument('feats', help='features of the utterance')

    #parser.add_argument('out', help='HTK binary file')
    parser.add_argument('out', help='kaldi ark file')
    parser.add_argument('key', help='key, utter id')

    args = parser.parse_args()

    with open(args.model, 'rb') as f:
        model = pickle.load(f)

    #X, infos = amdtk.readHtk(args.feats, infos=True)
    X, infos = amdtk.readKaldi(args.feats, infos=True)
    p = amdtk.phoneLoopForwardBackwardPosteriors(model, X, 
		output_states=args.hmm_states, ac_scale=args.ac_scale)

    #amdtk.writeHtk(args.out, p, infos[1])
    with open(args.out, 'wb') as f:
        kaldi_io.write_mat(f, p, args.key.encode())

if __name__ == '__main__':
    main()
else:
    raise ImportError('this script cannot be imported')
